// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Petstore.Data;

#nullable disable

namespace Petstore.Data.Migrations
{
    [DbContext(typeof(PetstoreCatalogContext))]
    [Migration("20260612102349_FullLegacyCatalogSeed")]
    partial class FullLegacyCatalogSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Petstore.Data.Entities.CategoryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("CatalogCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "FISH",
                            Name = "Fish"
                        },
                        new
                        {
                            Id = "DOGS",
                            Name = "Dogs"
                        },
                        new
                        {
                            Id = "REPTILES",
                            Name = "Reptiles"
                        },
                        new
                        {
                            Id = "CATS",
                            Name = "Cats"
                        },
                        new
                        {
                            Id = "BIRDS",
                            Name = "Birds"
                        });
                });

            modelBuilder.Entity("Petstore.Data.Entities.ItemEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("CatalogItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "EST-1",
                            Attributes = "[\"Large\",\"Cuddly\"]",
                            Currency = "USD",
                            Description = "Fresh Water fish from Japan",
                            Name = "Large Angelfish",
                            Price = 16.50m,
                            ProductId = "FI-SW-01"
                        },
                        new
                        {
                            Id = "EST-2",
                            Attributes = "[\"Small\"]",
                            Currency = "USD",
                            Description = "Fresh Water fish from Japan",
                            Name = "Small Angelfish",
                            Price = 16.50m,
                            ProductId = "FI-SW-01"
                        },
                        new
                        {
                            Id = "EST-3",
                            Attributes = "[\"Toothless\",\"Mean\"]",
                            Currency = "USD",
                            Description = "Salt Water fish from Australia",
                            Name = "Toothless Tiger Shark",
                            Price = 18.50m,
                            ProductId = "FI-SW-02"
                        },
                        new
                        {
                            Id = "EST-4",
                            Attributes = "[\"Spotted\"]",
                            Currency = "USD",
                            Description = "Fresh Water fish from Japan",
                            Name = "Spotted Koi",
                            Price = 18.50m,
                            ProductId = "FI-FW-01"
                        },
                        new
                        {
                            Id = "EST-5",
                            Attributes = "[\"Spotless\"]",
                            Currency = "USD",
                            Description = "Fresh Water fish from Japan",
                            Name = "Spotless Koi",
                            Price = 18.50m,
                            ProductId = "FI-FW-01"
                        },
                        new
                        {
                            Id = "EST-6",
                            Attributes = "[\"Male Adult\"]",
                            Currency = "USD",
                            Description = "Friendly dog from England",
                            Name = "Male Adult Bulldog",
                            Price = 18.50m,
                            ProductId = "K9-BD-01"
                        },
                        new
                        {
                            Id = "EST-7",
                            Attributes = "[\"Female Puppy\"]",
                            Currency = "USD",
                            Description = "Friendly dog from England",
                            Name = "Female Puppy Bulldog",
                            Price = 18.50m,
                            ProductId = "K9-BD-01"
                        },
                        new
                        {
                            Id = "EST-8",
                            Attributes = "[\"Male Puppy\"]",
                            Currency = "USD",
                            Description = "Cute dog from France",
                            Name = "Male Puppy Poodle",
                            Price = 18.50m,
                            ProductId = "K9-PO-02"
                        },
                        new
                        {
                            Id = "EST-9",
                            Attributes = "[\"Spotless Male Puppy\"]",
                            Currency = "USD",
                            Description = "Great dog for a Fire Station",
                            Name = "Spotless Male Puppy Dalmation",
                            Price = 18.50m,
                            ProductId = "K9-DL-01"
                        },
                        new
                        {
                            Id = "EST-10",
                            Attributes = "[\"Spotted Adult Female\"]",
                            Currency = "USD",
                            Description = "Great dog for a Fire Station",
                            Name = "Spotted Adult Female Dalmation",
                            Price = 18.50m,
                            ProductId = "K9-DL-01"
                        },
                        new
                        {
                            Id = "EST-11",
                            Attributes = "[\"Venomless\"]",
                            Currency = "USD",
                            Description = "More Bark than bite",
                            Name = "Venomless Rattlesnake",
                            Price = 18.50m,
                            ProductId = "RP-SN-01"
                        },
                        new
                        {
                            Id = "EST-12",
                            Attributes = "[\"Rattleless\"]",
                            Currency = "USD",
                            Description = "Doubles as a watch dog",
                            Name = "Rattleless Rattlesnake",
                            Price = 18.50m,
                            ProductId = "RP-SN-01"
                        },
                        new
                        {
                            Id = "EST-13",
                            Attributes = "[\"Green Adult\"]",
                            Currency = "USD",
                            Description = "Friendly green friend",
                            Name = "Green Adult Iguana",
                            Price = 12.50m,
                            ProductId = "RP-LI-02"
                        },
                        new
                        {
                            Id = "EST-14",
                            Attributes = "[\"Tailless\"]",
                            Currency = "USD",
                            Description = "Great for reducing mouse populations",
                            Name = "Tailless Manx",
                            Price = 58.50m,
                            ProductId = "FL-DSH-01"
                        },
                        new
                        {
                            Id = "EST-15",
                            Attributes = "[\"With tail\"]",
                            Currency = "USD",
                            Description = "Great for reducing mouse populations",
                            Name = "With tail Manx",
                            Price = 23.50m,
                            ProductId = "FL-DSH-01"
                        },
                        new
                        {
                            Id = "EST-16",
                            Attributes = "[\"Adult Female\"]",
                            Currency = "USD",
                            Description = "Friendly house cat, doubles as a princess",
                            Name = "Adult Female Persian",
                            Price = 93.50m,
                            ProductId = "FL-DLH-02"
                        },
                        new
                        {
                            Id = "EST-17",
                            Attributes = "[\"Adult Male\"]",
                            Currency = "USD",
                            Description = "Friendly house cat, doubles as a prince",
                            Name = "Adult Male Persian",
                            Price = 93.50m,
                            ProductId = "FL-DLH-02"
                        },
                        new
                        {
                            Id = "EST-18",
                            Attributes = "[\"Adult Male\"]",
                            Currency = "USD",
                            Description = "Great companion for up to 75 years",
                            Name = "Adult Male Amazon Parrot",
                            Price = 193.50m,
                            ProductId = "AV-CB-01"
                        },
                        new
                        {
                            Id = "EST-19",
                            Attributes = "[\"Adult Male\"]",
                            Currency = "USD",
                            Description = "Great stress reliever",
                            Name = "Adult Male Finch",
                            Price = 15.50m,
                            ProductId = "AV-SB-02"
                        },
                        new
                        {
                            Id = "EST-20",
                            Attributes = "[\"Adult Male\"]",
                            Currency = "USD",
                            Description = "Fresh Water fish from China",
                            Name = "Adult Male Goldfish",
                            Price = 5.50m,
                            ProductId = "FI-FW-02"
                        },
                        new
                        {
                            Id = "EST-21",
                            Attributes = "[\"Adult Female\"]",
                            Currency = "USD",
                            Description = "Fresh Water fish from China",
                            Name = "Adult Female Goldfish",
                            Price = 5.29m,
                            ProductId = "FI-FW-02"
                        },
                        new
                        {
                            Id = "EST-22",
                            Attributes = "[\"Adult Male\"]",
                            Currency = "USD",
                            Description = "Great hunting dog",
                            Name = "Adult Male Labrador Retriever",
                            Price = 135.50m,
                            ProductId = "K9-RT-02"
                        },
                        new
                        {
                            Id = "EST-23",
                            Attributes = "[\"Adult Female\"]",
                            Currency = "USD",
                            Description = "Great hunting dog",
                            Name = "Adult Female Labrador Retriever",
                            Price = 145.49m,
                            ProductId = "K9-RT-02"
                        },
                        new
                        {
                            Id = "EST-24",
                            Attributes = "[\"Male Puppy\"]",
                            Currency = "USD",
                            Description = "Great addition to a family",
                            Name = "Male Puppy Labrador Retriever",
                            Price = 255.50m,
                            ProductId = "K9-RT-02"
                        },
                        new
                        {
                            Id = "EST-25",
                            Attributes = "[\"Female Puppy\"]",
                            Currency = "USD",
                            Description = "Great hunting dog",
                            Name = "Female Puppy Labrador Retriever",
                            Price = 325.29m,
                            ProductId = "K9-RT-02"
                        },
                        new
                        {
                            Id = "EST-26",
                            Attributes = "[\"Adult Male\"]",
                            Currency = "USD",
                            Description = "Little yapper",
                            Name = "Adult Male Chihuahua",
                            Price = 125.50m,
                            ProductId = "K9-CW-01"
                        },
                        new
                        {
                            Id = "EST-27",
                            Attributes = "[\"Adult Female\"]",
                            Currency = "USD",
                            Description = "Great companion dog",
                            Name = "Adult Female Chihuahua",
                            Price = 155.29m,
                            ProductId = "K9-CW-01"
                        },
                        new
                        {
                            Id = "EST-28",
                            Attributes = "[\"Adult Female\"]",
                            Currency = "USD",
                            Description = "Great family dog",
                            Name = "Adult Female Golden Retriever",
                            Price = 155.29m,
                            ProductId = "K9-RT-01"
                        });
                });

            modelBuilder.Entity("Petstore.Data.Entities.ProductEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("CatalogProducts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "FI-SW-01",
                            CategoryId = "FISH",
                            Description = "Salt Water fish from Australia",
                            Name = "Angelfish"
                        },
                        new
                        {
                            Id = "FI-SW-02",
                            CategoryId = "FISH",
                            Description = "Salt Water fish from Australia",
                            Name = "Tiger Shark"
                        },
                        new
                        {
                            Id = "FI-FW-01",
                            CategoryId = "FISH",
                            Description = "Fresh Water fish from Japan",
                            Name = "Koi"
                        },
                        new
                        {
                            Id = "FI-FW-02",
                            CategoryId = "FISH",
                            Description = "Fresh Water fish from China",
                            Name = "Goldfish"
                        },
                        new
                        {
                            Id = "K9-BD-01",
                            CategoryId = "DOGS",
                            Description = "Friendly dog from England",
                            Name = "Bulldog"
                        },
                        new
                        {
                            Id = "K9-PO-02",
                            CategoryId = "DOGS",
                            Description = "Cute dog from France",
                            Name = "Poodle"
                        },
                        new
                        {
                            Id = "K9-DL-01",
                            CategoryId = "DOGS",
                            Description = "Great dog for a Fire Station",
                            Name = "Dalmation"
                        },
                        new
                        {
                            Id = "K9-RT-01",
                            CategoryId = "DOGS",
                            Description = "Great family dog",
                            Name = "Golden Retriever"
                        },
                        new
                        {
                            Id = "K9-RT-02",
                            CategoryId = "DOGS",
                            Description = "Great hunting dog",
                            Name = "Labrador Retriever"
                        },
                        new
                        {
                            Id = "K9-CW-01",
                            CategoryId = "DOGS",
                            Description = "Great companion dog",
                            Name = "Chihuahua"
                        },
                        new
                        {
                            Id = "RP-SN-01",
                            CategoryId = "REPTILES",
                            Description = "Doubles as a watch dog",
                            Name = "Rattlesnake"
                        },
                        new
                        {
                            Id = "RP-LI-02",
                            CategoryId = "REPTILES",
                            Description = "Friendly green friend",
                            Name = "Iguana"
                        },
                        new
                        {
                            Id = "FL-DSH-01",
                            CategoryId = "CATS",
                            Description = "Great for reducing mouse populations",
                            Name = "Manx"
                        },
                        new
                        {
                            Id = "FL-DLH-02",
                            CategoryId = "CATS",
                            Description = "Friendly house cat, doubles as a princess",
                            Name = "Persian"
                        },
                        new
                        {
                            Id = "AV-CB-01",
                            CategoryId = "BIRDS",
                            Description = "Great companion for up to 75 years",
                            Name = "Amazon Parrot"
                        },
                        new
                        {
                            Id = "AV-SB-02",
                            CategoryId = "BIRDS",
                            Description = "Great stress reliever",
                            Name = "Finch"
                        });
                });

            modelBuilder.Entity("Petstore.Data.Entities.ItemEntity", b =>
                {
                    b.HasOne("Petstore.Data.Entities.ProductEntity", "Product")
                        .WithMany("Items")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Petstore.Data.Entities.ProductEntity", b =>
                {
                    b.HasOne("Petstore.Data.Entities.CategoryEntity", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Petstore.Data.Entities.CategoryEntity", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Petstore.Data.Entities.ProductEntity", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
